version: "3"

services:
  # Databases:
  postgresql:
    container_name: "fintech-postgresql"
    image: postgres:15.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: product_engine, origination, scoring
    ports:
      - "5432:5432"
    networks:
      - fintech-network
    volumes:
      - ./tools/database-dev/configs/create-multiple-db-with-users.sh:/docker-entrypoint-initdb.d/create-multiple-db-with-users.sh:ro
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
      
  pgadmin:
    container_name: "fintech-pgadmin"
    image: dpage/pgadmin4
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c "
      cp -f /pgadmin4/pgpass /var/lib/pgadmin/;
      chmod 600 /var/lib/pgadmin/pgpass;
      /entrypoint.sh
      "
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "8080:80"
    networks:
      - fintech-network
    volumes:
      - ./tools/database-dev/configs/servers.json:/pgadmin4/servers.json:ro
      - ./tools/database-dev/configs/pgpass:/pgadmin4/pgpass:ro


  # Migrations:

  liquibase-pe:
    image: liquibase/liquibase:4.19.0
    container_name: liquibase-pe
    networks:
      - fintech-network
    volumes:
      - ./product_engine/migrations:/app
    command: --log-level ERROR  --defaultsFile=/app/dev.properties update
    depends_on:
      postgresql:
        condition: service_healthy
  
  liquibase-origination:
    image: liquibase/liquibase:4.19.0
    container_name: liquibase-origination
    networks:
      - fintech-network
    volumes:
      - ./origination/migrations:/app
    command: --log-level ERROR  --defaultsFile=/app/dev.properties update
    depends_on:
      postgresql:
        condition: service_healthy

  liquibase-scoring:
    image: liquibase/liquibase:4.19.0
    container_name: liquibase-scoring
    networks:
      - fintech-network
    volumes:
      - ./scoring/migrations:/app
    command: --log-level ERROR  --defaultsFile=/app/dev.properties update
    depends_on:
      postgresql:
        condition: service_healthy

  # Services
  product_engine:
    build:
      dockerfile: ./product_engine/src/Dockerfile
      context: ./
    container_name: product_engine
    networks:
      - fintech-network
    ports:
      - "80:80"
    env_file:
      - path: ./product_engine/src/config/.env
    depends_on:
      liquibase-pe:
        condition: service_completed_successfully

  origination:
    build:
      dockerfile: ./origination/src/Dockerfile
      context: ./
    container_name: origination
    networks:
      - fintech-network
    ports:
      - "90:90"
    env_file:
      - path: ./origination/src/config/.env
    depends_on:
      liquibase-origination:
        condition: service_completed_successfully

  gateway:
    build:
      dockerfile: ./gateway/src/Dockerfile
      context: ./
    container_name: gateway
    networks:
      - fintech-network
    ports:
      - "7022:7022"
    env_file:
      - path: ./gateway/src/config/.env
    depends_on:
      - product_engine
      - origination
  
  scoring:
    build:
      dockerfile: ./scoring/src/Dockerfile
      context: ./
    container_name: scoring
    networks:
      - fintech-network
    ports:
      - "8008:8008"
    env_file:
      - path: ./scoring/src/config/.env
    depends_on:
      liquibase-scoring:
        condition: service_completed_successfully

networks:
  fintech-network:
    name: "fintech-network"